apiVersion: v2
name: redis-ha
home: https://redis.io/
keywords:
- redis
- keyvalue
- database
version: 4.34.10
appVersion: 8.2.1
description: This Helm chart provides a highly available Redis implementation with a master/slave configuration and uses Sentinel sidecars for failover management
icon: https://img.icons8.com/external-tal-revivo-shadow-tal-revivo/24/external-redis-an-in-memory-data-structure-project-implementing-a-distributed-logo-shadow-tal-revivo.png
maintainers:
- email: alex@alex-esseling.de
  name: alexvanderberkel
sources:
- https://redis.io/download
- https://github.com/alexvanderberkel/charts/blob/master/charts/redis-ha
- https://github.com/oliver006/redis_exporter
